# ~/.config/hypr/colors.conf

# General colors
setenv  col.black     rgba(0c0c0cff)
setenv  col.white     rgba(ffffffff)

# Accent colors
setenv  col.red       rgba(c8102eff)
setenv  col.deep_red  rgba(981e32ff)
setenv  col.yellow    rgba(ffd900ff)
setenv  col.silver    rgba(b5b5b5ff)

# Window border
#setenv  col.border    rgba(ffffff33)
